/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Museu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author karinamunhos
 */
public class Inserir extends javax.swing.JFrame {

    private Connection connection;

    /**
     * Creates new form Inserir
     */
    public Inserir() {
        initComponents();
        try {
            this.connection = new ConnectionFactory().getConnection();
        } catch (SQLException e) {
            System.out.println("Erro ao se conectar");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Colecao = new javax.swing.JTextField();
        Data = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        Enviar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextArea();
        ID = new javax.swing.JFormattedTextField();
        Titulo = new javax.swing.JFormattedTextField();
        Pais = new javax.swing.JFormattedTextField();
        NomeArtista = new javax.swing.JFormattedTextField();
        Periodo = new javax.swing.JFormattedTextField();
        Emprestado = new javax.swing.JRadioButton();
        Permanente = new javax.swing.JRadioButton();
        Exposicao = new javax.swing.JFormattedTextField();
        Devolucao = new javax.swing.JFormattedTextField();
        Data2 = new javax.swing.JFormattedTextField();
        Ano = new javax.swing.JFormattedTextField();
        Custo = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Colecao.setText("Coleção");
        Colecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColecaoActionPerformed(evt);
            }
        });

        Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        Data.setText("dd/mm/aaaa");
        Data.setActionCommand("<Not Set>");
        Data.setInputVerifier(Data.getInputVerifier());
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });

        jLabel1.setText("Inserir Objeto de Arte ");

        Enviar.setBackground(new java.awt.Color(102, 0, 0));
        Enviar.setForeground(new java.awt.Color(255, 255, 255));
        Enviar.setText("Enviar");
        Enviar.setBorderPainted(false);
        Enviar.setOpaque(true);
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        Voltar.setBackground(new java.awt.Color(204, 0, 0));
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setText("Voltar");
        Voltar.setBorderPainted(false);
        Voltar.setOpaque(true);
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Descricao.setColumns(20);
        Descricao.setRows(5);
        Descricao.setText("Descição");
        jScrollPane2.setViewportView(Descricao);

        ID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        Titulo.setText("Título");

        Pais.setText("Pais");

        NomeArtista.setText("Nome do artista");
        NomeArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeArtistaActionPerformed(evt);
            }
        });

        Periodo.setText("Periodo");

        buttonGroup1.add(Emprestado);
        Emprestado.setSelected(true);
        Emprestado.setText("Emprestado");

        buttonGroup1.add(Permanente);
        Permanente.setText("Permanente");
        Permanente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermanenteActionPerformed(evt);
            }
        });

        Exposicao.setText("Em exposicao");

        Devolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        Devolucao.setText("dd/mm/aaaa");
        Devolucao.setActionCommand("<Not Set>");
        Devolucao.setInputVerifier(Data.getInputVerifier());
        Devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolucaoActionPerformed(evt);
            }
        });

        Data2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        Data2.setText("dd/mm/aaaa");
        Data2.setActionCommand("<Not Set>");
        Data2.setInputVerifier(Data.getInputVerifier());
        Data2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data2ActionPerformed(evt);
            }
        });

        Ano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        Custo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel2.setText("Emprestimo");

        jLabel3.setText("Devolução");

        jLabel4.setText("Aquisição");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Ano))
                            .addComponent(jScrollPane2)
                            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeArtista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(Periodo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(Custo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(Emprestado)
                                    .addComponent(Permanente)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Enviar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Voltar))
                                    .addComponent(Colecao, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(Devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(Data2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Exposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Emprestado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Colecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Permanente))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Data2)
                            .addComponent(Exposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Enviar)
                            .addComponent(Voltar))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColecaoActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        new PaginaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        if (!ID.getText().equals("") && !ID.getText().equals("ID") && !Descricao.getText().equals("") && !Descricao.getText().equals("Descrição") && !Titulo.getText().equals("") && !Titulo.getText().equals("Título")) {
            try {

                PreparedStatement stmt;
                stmt = this.connection.prepareStatement("SELECT * FROM OBJETO_ARTE WHERE NumId =" + ID.getText());
                ResultSet rs = stmt.executeQuery();
                if (!rs.next()) {

                    PreparedStatement stmt2;
                    stmt2 = this.connection.prepareStatement("INSERT INTO OBJETO_ARTE VALUES (" + ID.getText() + ", \"" + Pais.getText() + "\", \"" + Periodo.getText() + "\"," + Ano.getText() + ",\"" + Descricao.getText() + "\", \"" + Titulo.getText() + "\", \"" + NomeArtista.getText() + "\"," + Custo.getText() + ")");

                    if (Emprestado.isSelected()) {
                        PreparedStatement stmt3;
                        stmt3 = this.connection.prepareStatement("INSERT INTO EMPRESTADOS VALUES (" + ID.getText() + ", \"" + Colecao.getText() + "\" , str_to_date( \"" + Data.getText() + "\" , \"%d/%m/%Y\") " + ", str_to_date( \"" + Devolucao.getText() + "\" , \"%d/%m/%Y\")" + ")");
                        stmt2.execute();
                        stmt3.execute();
                        stmt3.close();
                    } else {
                        PreparedStatement stmt4;
                        stmt4 = this.connection.prepareStatement("INSERT INTO PERMANENTES VALUES (" + ID.getText() + ", str_to_date( \"" + Data2.getText() + "\" , \"%d/%m/%Y\")" + ", \"" + Exposicao.getText() + "\")");
                        stmt2.execute();
                        stmt4.execute();
                        stmt4.close();
                    }

                    stmt2.close();

                    JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
                    new PaginaPrincipal().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível realizar a inserção. Por favor, verifique seus dados.");

                }

                rs.close();
                stmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Não foi possível realizar a inserção. Por favor, verifique seus dados.");
                throw new RuntimeException(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar a inserção. Por favor, verifique seus dados.");

        }


    }//GEN-LAST:event_EnviarActionPerformed

    private void NomeArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeArtistaActionPerformed

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed

    }//GEN-LAST:event_DataActionPerformed

    private void DevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DevolucaoActionPerformed

    private void Data2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data2ActionPerformed

    private void PermanenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermanenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermanenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inserir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano;
    private javax.swing.JTextField Colecao;
    private javax.swing.JFormattedTextField Custo;
    private javax.swing.JFormattedTextField Data;
    private javax.swing.JFormattedTextField Data2;
    private javax.swing.JTextArea Descricao;
    private javax.swing.JFormattedTextField Devolucao;
    private javax.swing.JRadioButton Emprestado;
    private javax.swing.JButton Enviar;
    private javax.swing.JFormattedTextField Exposicao;
    private javax.swing.JFormattedTextField ID;
    private javax.swing.JFormattedTextField NomeArtista;
    private javax.swing.JFormattedTextField Pais;
    private javax.swing.JFormattedTextField Periodo;
    private javax.swing.JRadioButton Permanente;
    private javax.swing.JFormattedTextField Titulo;
    private javax.swing.JButton Voltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
